### ISSUE TITLE
Edit Rows

### ISSUE THREAD

**Issue by maxklenk** [GraFiddle/angular-chart#17]
Add options to edit which and how rows are displayed in the visualization.
### ToDo:
- [x] add optional enable row edit flag
- [x] add custom legend
- [x] add option to hide/show (remove/add?) rows
- [x] add function to hide/show (remove/add?) rows
- [x] add function to change row display (line,bar,area,scatter) 'only for multi chart'
- [x] add option to change the color of a row
- [x] add function to change the color of a row
- [ ] add hover highlighting for rows
- [x] add option to align row to y2-Axis
- [x] add function to change y-Axis
