### ISSUE TITLE
Add subchart zoom to canvas

### ISSUE THREAD

**Issue by maxklenk** [GraFiddle/angular-chart#21]
To explore the data it should be possible to zoom in the data in the xAxis using a subchart.

See: http://c3js.org/samples/options_subchart.html
### ToDo
- [x] add a toggle switch to show/hide a subchart
- [x] get zoom level on change
- [x] set zoom level
